[package]
name = "dustash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.36"
blocking = { path = "../blocking" }
crossbeam = "0.8"
futures = "0.3"
smallvec = "1.8"
